### PR TITLE
feature (homepage): Create the homepage

### PR DESCRIPTION
**Pull request by pngg**
**What does this PR do?**
Add the landing page for the application

**Description of Task to be completed?**
Design the app landing page

**How should this be manually tested?**
After cloning the repo, and cd into it
checkout ft-create-homepage-158316439
cd into the UI folder
open index.html using your favourite browser

**What are the relevant pivotal tracker stories?**
[#158316439](https://www.pivotaltracker.com/story/show/158316439)

**Screenshots**
screenshot_2018-06-13 ride my way home

### CODE REVIEW

**Comment by Derrickkip** [comment]
Nice design, the text in the image is not easily readable though, maybe add an overlay to the image or change the text color.

**Comment by DerKip** [comment]
I agree with @Derrickkip, try and make the text readable, maybe consider darkening the background image 
, otherwise, the design is nice.

**Comment by DerKip** [comment]
I agree with @Derrickkip, try and make the text readable, maybe consider darkening the background image 
, otherwise, the design is nice.

**Comment by pngg** [comment]
Thanks guys. This feedback is very helpful. Working on suggested changes.

**Comment by pngg** [comment]
Any comments for the update https://pngg.github.io/ride-my-way/UI/index.html

**Pull request merged**
