### PR TITLE
#158251728 Create user registration and sign in pages

### PR DESCRIPTION
**Pull request by pngg**
**What does this PR do?**
Create user registration flow to capture user information and provide for user login capabilities

**Description of Task to be completed?**
Create user registration and sign in pages

**How should this be manually tested?**
After cloning the repo, and cd into it
checkout ft-user-signup-flow-158251728
cd into the UI folder
open signup.html using your favourite browser

**What are the relevant pivotal tracker stories?**
[#158251728](https://www.pivotaltracker.com/story/show/158251728)

**Screenshots**

_User registration_
screenshot_2018-06-14 ride my way register

_Driver registration_
screenshot_2018-06-14 ride my way driver registration

_Login_
screenshot_2018-06-14 ride my way login

_Reset password_
screenshot_2018-06-14 ride my way password reset

### CODE REVIEW

**Comment by TheSteelGuy** [comment]
Awesome

**Comment by DerKip** [comment]
Looks Good ,🆒

**Comment by meshack-mbuvi** [comment]
The interface is looking good and is attractive. My observation is; when you are fixing or correcting something, that may be suited to be a `bug` but not a feature

**Comment by meshack-mbuvi** [comment]
This is how it looks when I view it using my tablet!
screenshot_2018-06-15-06-06-03

**Comment by pngg** [comment]
Thanks @meshack-mbuvi  looking into it.

**Pull request merged**
